### ISSUE TITLE
looking for feed back on external browser preview  - non windows os

### ISSUE THREAD

**Issue by skandasoft** [skandasoft/preview-plus#27]
Currently I have tested all external browser in windows . Looking for feedback/ the command normally used for other os for opening browsers

![image](https://cloud.githubusercontent.com/assets/9875379/7472548/4b388bdc-f2f9-11e4-8ed0-d592f742e306.png)

**Comment by jekriske** [comment]
Does not function at all under OS 10.10.3. No previewing of any kind. As a matter of fact, it locks up the atom window and it becomes unresponsive.
![screen shot 2015-05-15 at 4 29 41 pm](https://cloud.githubusercontent.com/assets/3432769/7661340/b9760d76-fb1f-11e4-8c62-e0629b05ad5c.png)

**Comment by skandasoft** [comment]
With the latest patch you would need to add your os details in the config..The package comes default witht the win32/win64 options..

  browser:
    title: 'Browser'
    type: 'boolean'
    default: true
    win32:
      IE:
        cmd: 'start iexplore '
      CHROME:
        cmd:  'start chrome '
      FF:
        cmd:  'start firefox '
      OPERA:
        cmd: 'start opera '
      SAFARI:
        cmd: 'start safari '

for window I need to use the command start safari followed by file name...and
so you would do a darwin config,in config.coffee..if you pr back with the correct commands for your os, others could use it.

**Comment by jekriske** [comment]
You can use:
```    
  darwin:
      CHROME:
        cmd: 'open -a "Google Chrome" '
      FF:
        cmd: 'open -a "Firefox" '
      SAFARI:
        cmd: 'open -a "Safari" ' 
```

Because there's no icon for safari, I just set an IE tag to open Safari. I'm sure if I had Opera installed it's the same command too...

Now, this will in fact open the browser but it will again make the Atom window unresponsive to clicks as the popup doesn't disappear. I did find that if I press ``cmd-r`` it will initialize the same popup for a symbol search and if I press it again it will finally close the dialog, clear the shadow layer, and allow clicking again. 
https://youtu.be/QaB2j5Dm98g
In the video I press ``cmd-r`` twice to clear it.
Ignore that it's set to Jade as Jade doesn't work... (it crashes because I don't have html2jade and the application doesn't check that it exists before trying to open it.)

The dialog should disappear correctly on it's own...

**Comment by skandasoft** [comment]
I updated the darwin os...but I am not sure I get the list box leaving the panel..But I tried removing explicity..with the latest patch ..check it out.

**Comment by jekriske** [comment]
Very close... the panel now gets correctly removed if I select any of the options except the external browser options. If I click on any of the external browser options the preview correctly opens in those browsers but the panel is still there in atom as if the parent.remove() code isn't being called.

**Comment by skandasoft** [comment]
Got that to..Check it out.

**Comment by jekriske** [comment]
Looks great! Works under Linux too... In Linux, most people will have their browsers in the default path so you can call them out by name and many distros will at least come with firefox so you can probably add FF to the default build:

```
    linux:
      FF: 
        cmd: 'firefox '
```

**Comment by skandasoft** [comment]
thanks for the inputs...added..
